/**
 * @fileoverview Core type definitions for the Stellar application.
 *
 * Entity types (database row shapes) are auto-generated by stellar-drive from
 * the schema definition in `src/lib/schema.ts`. This file re-exports them
 * with app-specific type narrowings (e.g. `GoalType` instead of `string`,
 * `DayOfWeek[]` instead of `unknown`).
 *
 * To update entity types, edit `src/lib/schema.ts` and save; the Vite plugin
 * regenerates `types.generated.ts` automatically.
 */

import type {
  GoalList as GenGoalList,
  Goal as GenGoal,
  DailyRoutineGoal as GenDailyRoutineGoal,
  DailyGoalProgress as GenDailyGoalProgress,
  TaskCategory as GenTaskCategory,
  Commitment as GenCommitment,
  DailyTask as GenDailyTask,
  LongTermTask as GenLongTermTask,
  FocusSettings as GenFocusSettings,
  FocusSession as GenFocusSession,
  BlockList as GenBlockList,
  BlockedWebsite as GenBlockedWebsite,
  Project as GenProject
} from './types.generated';

// =============================================================================
//  App-specific type aliases
// =============================================================================

/** Goal progress measurement strategy. */
export type GoalType = 'completion' | 'incremental' | 'progressive';

/** Numeric day-of-week constant aligned with `Date.getDay()`. */
export type DayOfWeek = 0 | 1 | 2 | 3 | 4 | 5 | 6;

/** Life area a commitment falls under. */
export type CommitmentSection = 'career' | 'projects' | 'personal';

/** Discriminator for long-term agenda items. */
export type AgendaItemType = 'task' | 'reminder';

/** Current phase of a Pomodoro-style focus session. */
export type FocusPhase = 'focus' | 'break' | 'idle';

/** Playback state of a focus session timer. */
export type FocusStatus = 'running' | 'paused' | 'stopped';

// =============================================================================
//  Entity types (narrowed from auto-generated)
// =============================================================================

/** A named collection of goals, optionally scoped to a project. */
export interface GoalList extends Omit<GenGoalList, 'project_id'> {
  project_id?: string | null;
}

/** A single goal belonging to a GoalList. */
export interface Goal extends Omit<GenGoal, 'type'> {
  type: GoalType;
}

/** A repeating daily routine goal. */
export interface DailyRoutineGoal extends Omit<GenDailyRoutineGoal, 'type' | 'active_days'> {
  type: GoalType;
  active_days: DayOfWeek[] | null;
}

/** A single day's progress for a DailyRoutineGoal. */
export type DailyGoalProgress = GenDailyGoalProgress;

/** A colour-coded category applied to tasks. */
export interface TaskCategory extends Omit<GenTaskCategory, 'project_id'> {
  project_id?: string | null;
}

/** A named commitment scoped to a life area. */
export interface Commitment extends Omit<GenCommitment, 'section' | 'project_id'> {
  section: CommitmentSection;
  project_id?: string | null;
}

/** A daily task, optionally with a runtime-joined category. */
export interface DailyTask extends Omit<GenDailyTask, 'long_term_task_id'> {
  long_term_task_id?: string | null;
  /** Runtime-only — joined from the linked long-term task's category. */
  category?: TaskCategory;
}

/** A long-term task or reminder on the agenda board. */
export interface LongTermTask extends Omit<GenLongTermTask, 'type'> {
  type: AgendaItemType;
}

/** User-configurable Pomodoro timer settings. */
export type FocusSettings = GenFocusSettings;

/** A single focus session record. */
export interface FocusSession extends Omit<GenFocusSession, 'phase' | 'status'> {
  phase: FocusPhase;
  status: FocusStatus;
}

/** A named collection of websites to block during focus sessions. */
export interface BlockList extends Omit<GenBlockList, 'active_days'> {
  active_days: DayOfWeek[] | null;
}

/** A single domain entry within a BlockList. */
export type BlockedWebsite = GenBlockedWebsite;

/** A top-level project. */
export type Project = GenProject;

// =============================================================================
//  Computed / aggregate types
// =============================================================================

/** Aggregated progress snapshot for a single calendar day. */
export interface DayProgress {
  date: string;
  totalGoals: number;
  completedGoals: number;
  completionPercentage: number;
}

/** A GoalList enriched with aggregate completion statistics. */
export interface GoalListWithProgress extends GoalList {
  totalGoals: number;
  completedGoals: number;
  completionPercentage: number;
}

/** A LongTermTask with its category eagerly joined. */
export interface LongTermTaskWithCategory extends LongTermTask {
  category?: TaskCategory;
}

/** A Project enriched with joined details and aggregate statistics. */
export interface ProjectWithDetails extends Project {
  tag?: TaskCategory | null;
  goalList?: GoalListWithProgress | null;
  taskStats?: { totalTasks: number; completedTasks: number } | null;
  combinedProgress?: number;
}
