<script lang="ts">
  /**
   * @fileoverview Email confirmation page — handles Supabase auth callbacks.
   *
   * This page is the target for email confirmation links generated by
   * Supabase (signup confirmations and device-verification OTPs).
   * It verifies the token, notifies any open login tab via
   * `BroadcastChannel`, and either closes itself or redirects.
   *
   * Flow:
   * 1. Extract `token_hash` and `type` from the URL query params.
   * 2. Call `verifyOtp` from the engine to validate the token.
   * 3. For device-verification types (`email` / `magiclink`), also
   *    call `trustPendingDevice` to mark the originating device trusted.
   * 4. Broadcast `AUTH_CONFIRMED` so the login tab can react.
   * 5. Attempt to close this tab; fall back to showing a "you can close"
   *    message if `window.close()` is blocked by the browser.
   */

  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { page } from '$app/stores';
  import { handleEmailConfirmation, broadcastAuthConfirmed } from 'stellar-drive/kit';

  // =============================================================================
  //  State
  // =============================================================================

  /** Current verification lifecycle status — drives UI rendering */
  let status: 'verifying' | 'success' | 'error' | 'redirecting' | 'can_close' = 'verifying';

  /** User-friendly error text shown when status is `'error'` */
  let errorMessage = '';

  // =============================================================================
  //  Constants
  // =============================================================================

  /** BroadcastChannel name shared with the login page */
  const CHANNEL_NAME = 'stellar-auth-channel';

  // =============================================================================
  //  Lifecycle — onMount verification flow
  // =============================================================================

  onMount(async () => {
    /* ── Read Supabase callback params ──── */
    const tokenHash = $page.url.searchParams.get('token_hash');
    const type = $page.url.searchParams.get('type');

    /* ── Token present → verify it ──── */
    if (tokenHash && type) {
      const result = await handleEmailConfirmation(
        tokenHash,
        type as 'signup' | 'email' | 'email_change' | 'magiclink'
      );

      if (!result.success) {
        status = 'error';
        errorMessage = result.error || 'Verification failed';
        return;
      }

      status = 'success';

      /* Brief pause so the user sees the success state */
      await new Promise((resolve) => setTimeout(resolve, 800));

      /* Hand off to the login tab or navigate directly */
      await focusOrRedirect();
    } else {
      /* No token in URL — nothing to verify; just redirect */
      await focusOrRedirect();
    }
  });

  // =============================================================================
  //  Helpers
  // =============================================================================

  /**
   * Broadcast a confirmation event to any listening login tab, then
   * attempt to close this browser tab. Falls back to a static
   * "you can close this tab" message when `window.close()` is denied.
   */
  async function focusOrRedirect() {
    status = 'redirecting';

    const type = $page.url.searchParams.get('type') || 'signup';

    const result = await broadcastAuthConfirmed(CHANNEL_NAME, type);

    if (result === 'no_broadcast') {
      /* BroadcastChannel unsupported — redirect to home directly */
      goto('/', { replaceState: true });
    } else {
      /* 'can_close' — window.close() was blocked by browser */
      setTimeout(() => {
        status = 'can_close';
      }, 200);
    }
  }
</script>

<svelte:head>
  <title>Confirming... - Stellar Planner</title>
</svelte:head>

<!-- ═══ Page Root ═══ -->
<div class="confirm-page">
  <!-- ═══ Cosmic Background ═══ -->
  <div class="background">
    <div class="void"></div>
    <div class="stars"></div>
    <div class="nebula nebula-1"></div>
    <div class="nebula nebula-2"></div>
  </div>

  <!-- ═══ Main Content Card ═══ -->
  <div class="content">
    <div class="card">
      <!-- ═══ Verifying State ═══ -->
      {#if status === 'verifying'}
        <div class="icon spinning">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path
              d="M12 2v4m0 12v4m-8-10h4m12 0h4m-5.66-5.66l-2.83 2.83m-5.02 5.02l-2.83 2.83m0-11.32l2.83 2.83m5.02 5.02l2.83 2.83"
            />
          </svg>
        </div>
        <h1>Verifying your email...</h1>
        <p>Please wait while we confirm your account.</p>

        <!-- ═══ Success State ═══ -->
      {:else if status === 'success'}
        <div class="icon success">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
            <path d="M20 6L9 17l-5-5" stroke-linecap="round" stroke-linejoin="round" />
          </svg>
        </div>
        <h1>Email Verified!</h1>
        <p>Your account has been confirmed. Redirecting you to Stellar...</p>

        <!-- ═══ Redirecting State ═══ -->
      {:else if status === 'redirecting'}
        <div class="icon">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0" />
            <path d="M12 7v5l3 3" />
          </svg>
        </div>
        <h1>Taking you to Stellar...</h1>
        <p>Just a moment...</p>

        <!-- ═══ Can-Close State (window.close failed) ═══ -->
      {:else if status === 'can_close'}
        <div class="icon success">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
            <path d="M20 6L9 17l-5-5" stroke-linecap="round" stroke-linejoin="round" />
          </svg>
        </div>
        <h1>You're all set!</h1>
        <p>Your email is verified. You can close this tab and return to Stellar.</p>

        <!-- ═══ Error State ═══ -->
      {:else if status === 'error'}
        <div class="icon error">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="10" />
            <line x1="15" y1="9" x2="9" y2="15" />
            <line x1="9" y1="9" x2="15" y2="15" />
          </svg>
        </div>
        <h1>Verification Failed</h1>
        <p class="error-message">{errorMessage}</p>
        <a href="/login" class="btn">Go to Login</a>
      {/if}
    </div>
  </div>
</div>

<style>
  /* ═══════════════════════════════════════════════════════════════════════════════════
     PAGE CONTAINER
     ═══════════════════════════════════════════════════════════════════════════════════ */

  .confirm-page {
    position: fixed;
    inset: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow: hidden;
  }

  /* ═══════════════════════════════════════════════════════════════════════════════════
     COSMIC BACKGROUND — Minimal starfield + nebula effects
     ═══════════════════════════════════════════════════════════════════════════════════ */

  .background {
    position: absolute;
    inset: 0;
    z-index: 0;
  }

  /* Deep-space radial gradient base */
  .void {
    position: absolute;
    inset: 0;
    background: radial-gradient(ellipse at center, #0a0a14 0%, #050510 100%);
  }

  /* Tiled star pattern — multi-layer radial gradients */
  .stars {
    position: absolute;
    inset: 0;
    background-image:
      radial-gradient(2px 2px at 20px 30px, #f0f0ff, transparent),
      radial-gradient(2px 2px at 40px 70px, rgba(108, 92, 231, 0.8), transparent),
      radial-gradient(1px 1px at 90px 40px, #f0f0ff, transparent),
      radial-gradient(2px 2px at 130px 80px, rgba(255, 121, 198, 0.6), transparent),
      radial-gradient(1px 1px at 160px 120px, #f0f0ff, transparent);
    background-size: 200px 200px;
    animation: twinkle 4s ease-in-out infinite;
  }

  /* Blurred nebula orbs for depth */
  .nebula {
    position: absolute;
    border-radius: 50%;
    filter: blur(80px);
    opacity: 0.4;
    animation: pulse 8s ease-in-out infinite;
  }

  .nebula-1 {
    width: 400px;
    height: 400px;
    background: radial-gradient(circle, rgba(108, 92, 231, 0.6) 0%, transparent 70%);
    top: 20%;
    left: 10%;
  }

  .nebula-2 {
    width: 300px;
    height: 300px;
    background: radial-gradient(circle, rgba(255, 121, 198, 0.5) 0%, transparent 70%);
    bottom: 20%;
    right: 15%;
    animation-delay: -4s;
  }

  /* ═══════════════════════════════════════════════════════════════════════════════════
     ANIMATIONS — Twinkle & Pulse
     ═══════════════════════════════════════════════════════════════════════════════════ */

  @keyframes twinkle {
    0%,
    100% {
      opacity: 1;
    }
    50% {
      opacity: 0.7;
    }
  }

  @keyframes pulse {
    0%,
    100% {
      transform: scale(1);
      opacity: 0.4;
    }
    50% {
      transform: scale(1.1);
      opacity: 0.5;
    }
  }

  /* ═══════════════════════════════════════════════════════════════════════════════════
     CONTENT & CARD — Glassmorphism card centered on page
     ═══════════════════════════════════════════════════════════════════════════════════ */

  .content {
    position: relative;
    z-index: 1;
    padding: 20px;
  }

  .card {
    background: linear-gradient(165deg, rgba(15, 15, 30, 0.95) 0%, rgba(20, 20, 40, 0.9) 100%);
    border: 1px solid rgba(108, 92, 231, 0.25);
    border-radius: 24px;
    padding: 48px;
    text-align: center;
    max-width: 400px;
    backdrop-filter: blur(24px);
    box-shadow:
      0 32px 80px rgba(0, 0, 0, 0.5),
      0 0 0 1px rgba(255, 255, 255, 0.03) inset,
      0 0 100px rgba(108, 92, 231, 0.1);
  }

  /* ═══════════════════════════════════════════════════════════════════════════════════
     STATUS ICONS — Circular icon badges with gradient backgrounds
     ═══════════════════════════════════════════════════════════════════════════════════ */

  .icon {
    width: 64px;
    height: 64px;
    margin: 0 auto 24px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: linear-gradient(135deg, rgba(108, 92, 231, 0.2) 0%, rgba(255, 121, 198, 0.15) 100%);
    border-radius: 50%;
    color: var(--color-primary, #6c5ce7);
  }

  .icon svg {
    width: 32px;
    height: 32px;
  }

  /* Spinning loader variant */
  .icon.spinning svg {
    animation: spin 1.5s linear infinite;
  }

  /* Success variant — green gradient */
  .icon.success {
    background: linear-gradient(135deg, rgba(38, 222, 129, 0.2) 0%, rgba(0, 212, 255, 0.15) 100%);
    color: var(--color-success, #26de81);
  }

  /* Error variant — red gradient */
  .icon.error {
    background: linear-gradient(
      135deg,
      rgba(255, 107, 107, 0.2) 0%,
      rgba(255, 121, 198, 0.15) 100%
    );
    color: var(--color-red, #ff6b6b);
  }

  @keyframes spin {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }

  /* ═══════════════════════════════════════════════════════════════════════════════════
     TYPOGRAPHY
     ═══════════════════════════════════════════════════════════════════════════════════ */

  h1 {
    margin: 0 0 12px;
    font-size: 24px;
    font-weight: 600;
    color: var(--color-text, #f0f0ff);
    letter-spacing: -0.3px;
  }

  p {
    margin: 0;
    font-size: 15px;
    line-height: 1.5;
    color: var(--color-text-secondary, #c8c8e0);
  }

  .error-message {
    color: var(--color-red, #ff6b6b);
    margin-bottom: 24px;
  }

  /* ═══════════════════════════════════════════════════════════════════════════════════
     ACTION BUTTON — "Go to Login" link styled as a button
     ═══════════════════════════════════════════════════════════════════════════════════ */

  .btn {
    display: inline-block;
    margin-top: 8px;
    padding: 12px 32px;
    background: linear-gradient(135deg, #6c5ce7 0%, #8b7cf0 100%);
    color: #ffffff;
    font-size: 15px;
    font-weight: 600;
    text-decoration: none;
    border-radius: 12px;
    transition: all 0.2s ease;
  }

  .btn:hover {
    transform: translateY(-2px);
    box-shadow: 0 8px 24px rgba(108, 92, 231, 0.4);
  }
</style>
